# Generated by Django 5.0.3 on 2024-03-19 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanfelo_Csoportbontasi_szempont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=255)),
                ('magyarazat', models.TextField()),
            ],
            options={
                'verbose_name': 'Csoportbontási szempont',
                'verbose_name_plural': 'Csoportbontási szempontok',
            },
        ),
        migrations.CreateModel(
            name='Tanfelo_Tantargy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('tantargygondozoi', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tantárgy',
                'verbose_name_plural': 'Tantárgyak',
            },
        ),
        migrations.CreateModel(
            name='Tanfelo_Tanar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tantargyai', models.ManyToManyField(to='app_tanfelo.tanfelo_tantargy')),
            ],
            options={
                'verbose_name': 'Tanár',
                'verbose_name_plural': 'Tanárok',
            },
        ),
        migrations.CreateModel(
            name='Tanfelo_Tanulocsoport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('kreta', models.CharField(max_length=255)),
                ('lehetseges_tantargyai', models.ManyToManyField(to='app_tanfelo.tanfelo_tantargy')),
            ],
            options={
                'verbose_name': 'Tanulócsoport',
                'verbose_name_plural': 'Tanulócsoportok',
            },
        ),
        migrations.CreateModel(
            name='Tanfelo_Kmk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oraszam', models.IntegerField()),
                ('tanar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tanfelo.tanfelo_tanar')),
                ('tantargy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tanfelo.tanfelo_tantargy')),
                ('tanulocsoport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tanfelo.tanfelo_tanulocsoport')),
            ],
            options={
                'verbose_name': 'Ki tanít, mit, kinek?',
                'verbose_name_plural': 'Ki tanít, mit, kinek?',
            },
        ),
        migrations.CreateModel(
            name='Tanfelo_Csoportbontas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szempont', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tanfelo.tanfelo_csoportbontasi_szempont')),
                ('resz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resz', to='app_tanfelo.tanfelo_tanulocsoport')),
                ('univerzum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='univerzum', to='app_tanfelo.tanfelo_tanulocsoport')),
            ],
            options={
                'verbose_name': 'Csoportbontás',
                'verbose_name_plural': 'Csoportbontások',
            },
        ),
    ]
